### ISSUE TITLE
The route is not being determined when the middleware needs it

### ISSUE THREAD

**Issue by jcchavezs** [slimphp-api/slim-acl#4]
By the time the Guards are being checked, the route is not in the Request object. This can be solved by a change in configuration so it would be fair to add to the readme.

**Comment by gabriel403** [comment]
@jcchavezs I honestly thought I had, oops! I'll add it into the docs, thanks :)

`determineRouteBeforeAppMiddleware`

**Comment by jcchavezs** [comment]
@gabriel403 I just added. There is a PR :smile:.
